// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-job/internal/conf"
	"review-job/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(kafka *conf.Kafka, elasticSearch *conf.ElasticSearch, logger log.Logger) (*kratos.App, func(), error) {
	reader := server.NewKafkaReader(kafka)
	elasticSearchClient, err := server.NewElasticSearchClient(elasticSearch)
	if err != nil {
		return nil, nil, err
	}
	reviewWorker := server.NewReviewWorker(reader, elasticSearchClient, logger)
	app := newApp(logger, reviewWorker)
	return app, func() {
	}, nil
}
