// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-operator/internal/biz"
	"review-operator/internal/conf"
	"review-operator/internal/data"
	"review-operator/internal/server"
	"review-operator/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := service.NewDiscovery(registry)
	appealClient := service.NewAppealClient(discovery, registry)
	dataData, cleanup, err := data.NewData(confData, appealClient, logger)
	if err != nil {
		return nil, nil, err
	}
	operatorRepo := data.NewOperatorRepo(dataData, logger)
	operatorUsecase := biz.NewOperatorUsecase(operatorRepo, logger)
	operatorService := service.NewOperatorService(operatorUsecase)
	grpcServer := server.NewGRPCServer(confServer, operatorService, logger)
	httpServer := server.NewHTTPServer(confServer, operatorService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
