// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q      = new(Query)
	Appeal *appeal
	Reply  *reply
	Review *review
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Appeal = &Q.Appeal
	Reply = &Q.Reply
	Review = &Q.Review
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:     db,
		Appeal: newAppeal(db, opts...),
		Reply:  newReply(db, opts...),
		Review: newReview(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Appeal appeal
	Reply  reply
	Review review
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Appeal: q.Appeal.clone(db),
		Reply:  q.Reply.clone(db),
		Review: q.Review.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Appeal: q.Appeal.replaceDB(db),
		Reply:  q.Reply.replaceDB(db),
		Review: q.Review.replaceDB(db),
	}
}

type queryCtx struct {
	Appeal IAppealDo
	Reply  IReplyDo
	Review IReviewDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Appeal: q.Appeal.WithContext(ctx),
		Reply:  q.Reply.WithContext(ctx),
		Review: q.Review.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
