// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.27.3
// source: api/operator/v1/operator.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOperatorResolveAppeal = "/api.operator.v1.Operator/ResolveAppeal"

type OperatorHTTPServer interface {
	ResolveAppeal(context.Context, *ResolveAppealRequest) (*ResolveAppealReply, error)
}

func RegisterOperatorHTTPServer(s *http.Server, srv OperatorHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/appeal/resolve", _Operator_ResolveAppeal0_HTTP_Handler(srv))
}

func _Operator_ResolveAppeal0_HTTP_Handler(srv OperatorHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveAppealRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOperatorResolveAppeal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveAppeal(ctx, req.(*ResolveAppealRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveAppealReply)
		return ctx.Result(200, reply)
	}
}

type OperatorHTTPClient interface {
	ResolveAppeal(ctx context.Context, req *ResolveAppealRequest, opts ...http.CallOption) (rsp *ResolveAppealReply, err error)
}

type OperatorHTTPClientImpl struct {
	cc *http.Client
}

func NewOperatorHTTPClient(client *http.Client) OperatorHTTPClient {
	return &OperatorHTTPClientImpl{client}
}

func (c *OperatorHTTPClientImpl) ResolveAppeal(ctx context.Context, in *ResolveAppealRequest, opts ...http.CallOption) (*ResolveAppealReply, error) {
	var out ResolveAppealReply
	pattern := "/v1/appeal/resolve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOperatorResolveAppeal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
