server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
kafka:
  brokers:
    - "localhost:9092"
  group_id: "review-job"
  topic: "review"
elastic_search:
  addrs:
    - "http://localhost:9200"
  index: "review"