// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/reply/v1/reply.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplyRequestMultiError, or nil if none found.
func (m *CreateReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReviewID

	// no validation rules for UserID

	if l := utf8.RuneCountInString(m.GetContent()); l < 1 || l > 1024 {
		err := CreateReplyRequestValidationError{
			field:  "Content",
			reason: "value length must be between 1 and 1024 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateReplyRequestMultiError(errors)
	}

	return nil
}

// CreateReplyRequestMultiError is an error wrapping multiple validation errors
// returned by CreateReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplyRequestMultiError) AllErrors() []error { return m }

// CreateReplyRequestValidationError is the validation error returned by
// CreateReplyRequest.Validate if the designated constraints aren't met.
type CreateReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplyRequestValidationError) ErrorName() string {
	return "CreateReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplyRequestValidationError{}

// Validate checks the field values on CreateReplyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplyReplyMultiError, or nil if none found.
func (m *CreateReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplyID

	if len(errors) > 0 {
		return CreateReplyReplyMultiError(errors)
	}

	return nil
}

// CreateReplyReplyMultiError is an error wrapping multiple validation errors
// returned by CreateReplyReply.ValidateAll() if the designated constraints
// aren't met.
type CreateReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplyReplyMultiError) AllErrors() []error { return m }

// CreateReplyReplyValidationError is the validation error returned by
// CreateReplyReply.Validate if the designated constraints aren't met.
type CreateReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplyReplyValidationError) ErrorName() string { return "CreateReplyReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplyReplyValidationError{}

// Validate checks the field values on UpdateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReplyRequestMultiError, or nil if none found.
func (m *UpdateReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateReplyRequestMultiError(errors)
	}

	return nil
}

// UpdateReplyRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReplyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReplyRequestMultiError) AllErrors() []error { return m }

// UpdateReplyRequestValidationError is the validation error returned by
// UpdateReplyRequest.Validate if the designated constraints aren't met.
type UpdateReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReplyRequestValidationError) ErrorName() string {
	return "UpdateReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReplyRequestValidationError{}

// Validate checks the field values on UpdateReplyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReplyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReplyReplyMultiError, or nil if none found.
func (m *UpdateReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateReplyReplyMultiError(errors)
	}

	return nil
}

// UpdateReplyReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateReplyReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReplyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReplyReplyMultiError) AllErrors() []error { return m }

// UpdateReplyReplyValidationError is the validation error returned by
// UpdateReplyReply.Validate if the designated constraints aren't met.
type UpdateReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReplyReplyValidationError) ErrorName() string { return "UpdateReplyReplyValidationError" }

// Error satisfies the builtin error interface
func (e UpdateReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReplyReplyValidationError{}

// Validate checks the field values on DeleteReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReplyRequestMultiError, or nil if none found.
func (m *DeleteReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteReplyRequestMultiError(errors)
	}

	return nil
}

// DeleteReplyRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReplyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReplyRequestMultiError) AllErrors() []error { return m }

// DeleteReplyRequestValidationError is the validation error returned by
// DeleteReplyRequest.Validate if the designated constraints aren't met.
type DeleteReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReplyRequestValidationError) ErrorName() string {
	return "DeleteReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReplyRequestValidationError{}

// Validate checks the field values on DeleteReplyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReplyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReplyReplyMultiError, or nil if none found.
func (m *DeleteReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteReplyReplyMultiError(errors)
	}

	return nil
}

// DeleteReplyReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteReplyReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReplyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReplyReplyMultiError) AllErrors() []error { return m }

// DeleteReplyReplyValidationError is the validation error returned by
// DeleteReplyReply.Validate if the designated constraints aren't met.
type DeleteReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReplyReplyValidationError) ErrorName() string { return "DeleteReplyReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeleteReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReplyReplyValidationError{}

// Validate checks the field values on GetReplyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReplyRequestMultiError, or nil if none found.
func (m *GetReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetReplyRequestMultiError(errors)
	}

	return nil
}

// GetReplyRequestMultiError is an error wrapping multiple validation errors
// returned by GetReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type GetReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReplyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReplyRequestMultiError) AllErrors() []error { return m }

// GetReplyRequestValidationError is the validation error returned by
// GetReplyRequest.Validate if the designated constraints aren't met.
type GetReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReplyRequestValidationError) ErrorName() string { return "GetReplyRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReplyRequestValidationError{}

// Validate checks the field values on GetReplyReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReplyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetReplyReplyMultiError, or
// nil if none found.
func (m *GetReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetReplyReplyMultiError(errors)
	}

	return nil
}

// GetReplyReplyMultiError is an error wrapping multiple validation errors
// returned by GetReplyReply.ValidateAll() if the designated constraints
// aren't met.
type GetReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReplyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReplyReplyMultiError) AllErrors() []error { return m }

// GetReplyReplyValidationError is the validation error returned by
// GetReplyReply.Validate if the designated constraints aren't met.
type GetReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReplyReplyValidationError) ErrorName() string { return "GetReplyReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReplyReplyValidationError{}

// Validate checks the field values on ListReplyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReplyRequestMultiError, or nil if none found.
func (m *ListReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListReplyRequestMultiError(errors)
	}

	return nil
}

// ListReplyRequestMultiError is an error wrapping multiple validation errors
// returned by ListReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type ListReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplyRequestMultiError) AllErrors() []error { return m }

// ListReplyRequestValidationError is the validation error returned by
// ListReplyRequest.Validate if the designated constraints aren't met.
type ListReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplyRequestValidationError) ErrorName() string { return "ListReplyRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplyRequestValidationError{}

// Validate checks the field values on ListReplyReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListReplyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListReplyReplyMultiError,
// or nil if none found.
func (m *ListReplyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListReplyReplyMultiError(errors)
	}

	return nil
}

// ListReplyReplyMultiError is an error wrapping multiple validation errors
// returned by ListReplyReply.ValidateAll() if the designated constraints
// aren't met.
type ListReplyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplyReplyMultiError) AllErrors() []error { return m }

// ListReplyReplyValidationError is the validation error returned by
// ListReplyReply.Validate if the designated constraints aren't met.
type ListReplyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplyReplyValidationError) ErrorName() string { return "ListReplyReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListReplyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplyReplyValidationError{}
