// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: api/reply/v1/reply.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewID string   `protobuf:"bytes,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	UserID   string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Pictures []string `protobuf:"bytes,4,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Videos   []string `protobuf:"bytes,5,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReplyRequest) GetReviewID() string {
	if x != nil {
		return x.ReviewID
	}
	return ""
}

func (x *CreateReplyRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReplyRequest) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

func (x *CreateReplyRequest) GetVideos() []string {
	if x != nil {
		return x.Videos
	}
	return nil
}

type CreateReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplyID string `protobuf:"bytes,1,opt,name=replyID,proto3" json:"replyID,omitempty"`
}

func (x *CreateReplyReply) Reset() {
	*x = CreateReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReply) ProtoMessage() {}

func (x *CreateReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReply.ProtoReflect.Descriptor instead.
func (*CreateReplyReply) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReplyReply) GetReplyID() string {
	if x != nil {
		return x.ReplyID
	}
	return ""
}

type UpdateReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyRequest) Reset() {
	*x = UpdateReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyRequest) ProtoMessage() {}

func (x *UpdateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{2}
}

type UpdateReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReplyReply) Reset() {
	*x = UpdateReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyReply) ProtoMessage() {}

func (x *UpdateReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyReply.ProtoReflect.Descriptor instead.
func (*UpdateReplyReply) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{3}
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{4}
}

type DeleteReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReplyReply) Reset() {
	*x = DeleteReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyReply) ProtoMessage() {}

func (x *DeleteReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyReply.ProtoReflect.Descriptor instead.
func (*DeleteReplyReply) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{5}
}

type GetReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyRequest) Reset() {
	*x = GetReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyRequest) ProtoMessage() {}

func (x *GetReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyRequest.ProtoReflect.Descriptor instead.
func (*GetReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{6}
}

type GetReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReplyReply) Reset() {
	*x = GetReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyReply) ProtoMessage() {}

func (x *GetReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyReply.ProtoReflect.Descriptor instead.
func (*GetReplyReply) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{7}
}

type ListReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyRequest) Reset() {
	*x = ListReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyRequest) ProtoMessage() {}

func (x *ListReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyRequest.ProtoReflect.Descriptor instead.
func (*ListReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{8}
}

type ListReplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReplyReply) Reset() {
	*x = ListReplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reply_v1_reply_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplyReply) ProtoMessage() {}

func (x *ListReplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_reply_v1_reply_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplyReply.ProtoReflect.Descriptor instead.
func (*ListReplyReply) Descriptor() ([]byte, []int) {
	return file_api_reply_v1_reply_proto_rawDescGZIP(), []int{9}
}

var File_api_reply_v1_reply_proto protoreflect.FileDescriptor

var file_api_reply_v1_reply_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa2, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07,
	0x72, 0x05, 0x10, 0x01, 0x18, 0x80, 0x08, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x49, 0x44, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xa3, 0x03, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x65, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x20, 0x5a, 0x1e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_reply_v1_reply_proto_rawDescOnce sync.Once
	file_api_reply_v1_reply_proto_rawDescData = file_api_reply_v1_reply_proto_rawDesc
)

func file_api_reply_v1_reply_proto_rawDescGZIP() []byte {
	file_api_reply_v1_reply_proto_rawDescOnce.Do(func() {
		file_api_reply_v1_reply_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_reply_v1_reply_proto_rawDescData)
	})
	return file_api_reply_v1_reply_proto_rawDescData
}

var file_api_reply_v1_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_reply_v1_reply_proto_goTypes = []any{
	(*CreateReplyRequest)(nil), // 0: api.reply.v1.CreateReplyRequest
	(*CreateReplyReply)(nil),   // 1: api.reply.v1.CreateReplyReply
	(*UpdateReplyRequest)(nil), // 2: api.reply.v1.UpdateReplyRequest
	(*UpdateReplyReply)(nil),   // 3: api.reply.v1.UpdateReplyReply
	(*DeleteReplyRequest)(nil), // 4: api.reply.v1.DeleteReplyRequest
	(*DeleteReplyReply)(nil),   // 5: api.reply.v1.DeleteReplyReply
	(*GetReplyRequest)(nil),    // 6: api.reply.v1.GetReplyRequest
	(*GetReplyReply)(nil),      // 7: api.reply.v1.GetReplyReply
	(*ListReplyRequest)(nil),   // 8: api.reply.v1.ListReplyRequest
	(*ListReplyReply)(nil),     // 9: api.reply.v1.ListReplyReply
}
var file_api_reply_v1_reply_proto_depIdxs = []int32{
	0, // 0: api.reply.v1.Reply.CreateReply:input_type -> api.reply.v1.CreateReplyRequest
	2, // 1: api.reply.v1.Reply.UpdateReply:input_type -> api.reply.v1.UpdateReplyRequest
	4, // 2: api.reply.v1.Reply.DeleteReply:input_type -> api.reply.v1.DeleteReplyRequest
	6, // 3: api.reply.v1.Reply.GetReply:input_type -> api.reply.v1.GetReplyRequest
	8, // 4: api.reply.v1.Reply.ListReply:input_type -> api.reply.v1.ListReplyRequest
	1, // 5: api.reply.v1.Reply.CreateReply:output_type -> api.reply.v1.CreateReplyReply
	3, // 6: api.reply.v1.Reply.UpdateReply:output_type -> api.reply.v1.UpdateReplyReply
	5, // 7: api.reply.v1.Reply.DeleteReply:output_type -> api.reply.v1.DeleteReplyReply
	7, // 8: api.reply.v1.Reply.GetReply:output_type -> api.reply.v1.GetReplyReply
	9, // 9: api.reply.v1.Reply.ListReply:output_type -> api.reply.v1.ListReplyReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_reply_v1_reply_proto_init() }
func file_api_reply_v1_reply_proto_init() {
	if File_api_reply_v1_reply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_reply_v1_reply_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reply_v1_reply_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListReplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_reply_v1_reply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reply_v1_reply_proto_goTypes,
		DependencyIndexes: file_api_reply_v1_reply_proto_depIdxs,
		MessageInfos:      file_api_reply_v1_reply_proto_msgTypes,
	}.Build()
	File_api_reply_v1_reply_proto = out.File
	file_api_reply_v1_reply_proto_rawDesc = nil
	file_api_reply_v1_reply_proto_goTypes = nil
	file_api_reply_v1_reply_proto_depIdxs = nil
}
